devices:
  - name: Chateau
    address: 192.168.0.1
    user: prometheus
    password: FOOO
 
features:
  bgp: false
  dhcp: true
  dhcpv6: true
  dhcpl: true
  routes: true
  firmware: true  
  pools: true
  monitor: true
  health: true
  resource: true
  interface: true
  health: true
  pool: true
  wlansta: true
  wlanif: true
  lte: false
  netwatch: true
